# Numpy

Why NUMPY?
1. performs fast operation (beacuse of vectorization).
2. Numpy arrays can be treated as vector and matrices from linear algebra.

In [24]:
!pip install numpy
import timeit
lst=[1,2,3,4,5,6,7,8,9]
# for i in lst:
#     i=i**2
# print(lst)
%timeit [i**2 for i in lst]

Defaulting to user installation because normal site-packages is not writeable
5.02 µs ± 152 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [20]:
import numpy as np

arr=np.array(lst)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr+1#adding 1 to each element in array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
%timeit arr**2

1.4 µs ± 10.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [25]:
#fundamental element in numpy is homogenous array.
l=[1,2,3,4,5]
np_array=np.array(l)
np_array

array([1, 2, 3, 4, 5])

In [26]:
#dimension and shape 
np_array.ndim

1

In [29]:
np_array.shape

(5,)

In [34]:
#np.arange
new_arr=np.arange(3,11,2)
new_arr.ndim

1

In [35]:
new_arr.shape

(4,)

In [38]:
lst_2d=[[1,2,3],[4,5,6],[7,8,9]]
arr_2d=np.array(lst_2d)
arr_2d.ndim

2

In [39]:
arr_2d.shape

(3, 3)

In [40]:
#special arrays in numpy
np.zeros((4,4))#double brac. makes it tuple


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.diag([1,2,3])#diagonal element

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [43]:
np.identity(4)#identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Indexing and masking

In [52]:
#random in numpy
newarr=np.random.randint(10,20,(5,4))

In [53]:
newarr

array([[17, 11, 15, 10],
       [14, 11, 13, 15],
       [15, 11, 19, 12],
       [17, 14, 14, 15],
       [19, 13, 19, 17]])

In [54]:
newarr[0]#first row

array([17, 11, 15, 10])

In [55]:
newarr[-1]

array([19, 13, 19, 17])

In [56]:
newarr[0][0]

17

In [57]:
newarr[0,0]

17

In [58]:
#array slicing
newarr[2:5,1:4]

array([[11, 19, 12],
       [14, 14, 15],
       [13, 19, 17]])

In [59]:
newarr[1:]

array([[14, 11, 13, 15],
       [15, 11, 19, 12],
       [17, 14, 14, 15],
       [19, 13, 19, 17]])

In [61]:
newarr[:,2]# element of all rows of second coloumn

array([15, 13, 19, 14, 19])

In [64]:
#maskin
newarr>15

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False,  True, False],
       [ True, False, False, False],
       [ True, False,  True,  True]])

In [68]:
mask=newarr>14
print(mask)

[[ True False  True False]
 [False False False  True]
 [ True False  True False]
 [ True False False  True]
 [ True False  True  True]]


In [69]:
np.sum(mask)#you will know how many element are greater than 14

10

In [71]:
#making some element zero
newarr[2:,2:]=0
newarr

array([[17, 11, 15, 10],
       [14, 11, 13, 15],
       [15, 11,  0,  0],
       [17, 14,  0,  0],
       [19, 13,  0,  0]])

In [75]:
#basic operation on numpy array -element wise operators
a=np.array([10,20,30,40])
b=np.arange(1,5)
print(a)
print(b)

[10 20 30 40]
[1 2 3 4]


In [74]:
a+b

array([11, 22, 33, 44])

In [76]:
a-b

array([ 9, 18, 27, 36])

In [77]:
a*b

array([ 10,  40,  90, 160])

In [78]:
b**2

array([ 1,  4,  9, 16], dtype=int32)

In [79]:
a>15


array([False,  True,  True,  True])

In [80]:
np.log(b)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [81]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

Matrix product
Rule-Multiplication of matreix is only allow when no of col of first matrix is equal to no of rows of second matrix
np.dot(A,B)

In [82]:
np.dot(a,b)

300

In [83]:
ar=np.arange(0,24)

In [84]:
ar.shape

(24,)

In [96]:
a2d=ar.reshape(6,4)#for reshaping the no of element should be same
a2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [87]:
np.sqrt(ar)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [88]:
np.sum(a)

100

In [89]:
np.max(a)

40

In [90]:
np.mean(a)

25.0

In [91]:
np.std(a)

11.180339887498949

In [92]:
np.sum(a,axis=0)

100

In [97]:
np.sum(a2d,axis=1)

array([ 6, 22, 38, 54, 70, 86])

# Shape manipulation

In [98]:
a2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [100]:
a2d.reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [101]:
a2d.T#transpose of the matrix

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

#stacking of arrays
1. vstack
2. hstack
use mainly for concating array

In [107]:
a=np.random.randint(0,10,(2,2))
b=np.random.randint(0,10,(2,2))
a

array([[2, 9],
       [4, 2]])

In [108]:
b

array([[8, 2],
       [3, 9]])

In [109]:
np.hstack((a,b))

array([[2, 9, 8, 2],
       [4, 2, 3, 9]])

In [110]:
np.vstack((a,b))

array([[2, 9],
       [4, 2],
       [8, 2],
       [3, 9]])

#Broadcasting
according to rule we can perform operations only when they have same shape.
but because of broadcasting we can perform the operation on 2 arrays of different shapes. It is happen beacuse the smaller array will repeat itsel and convert to the same shape as of another array.

In [111]:
A=np.random.randint(0,10,(3,3))
a=np.array([1,2,3])
A.shape

(3, 3)

In [112]:
a.shape

(3,)

In [113]:
a+A

array([[ 4,  3,  5],
       [ 3,  6, 10],
       [ 6,  9,  5]])

# vectorization
performing operation directly on array

In [121]:
p1=np.array([1,2])
p2=np.array([5,5])

#by normal method
#Eucladian distance
s=0
for i in range(2):
    s+=(p2[i]-p1[i])**2
s**0.5

5.0

In [123]:
#by vectorization
np.sqrt(np.sum((p2-p1)**2))

5.0

In [5]:
import numpy as np
np.__version__

'1.21.5'